# Generated by Django 4.2.30 on 2026-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='niveau_licence',
            field=models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Licence 4', 'Licence 4')], default='Licence 1', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
