# Generated by Django 4.2.30 on 2026-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_studentprofile_niveau_licence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('departement', models.CharField(default='NTIC', max_length=150)),
                ('niveau_licence', models.CharField(default='Licence 3', max_length=50)),
            ],
        ),
    ]
